version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    default_reviewers:
      - FundingOptions/backend
    allowed_updates:
      - match:
          update_type: all
          update_type: all

{%- if cookiecutter.hosting_type == 'serverless' %}
  - package_manager: javascript
    directory: /
    update_schedule: live
    default_reviewers:
      - FundingOptions/backend
    allowed_updates:
      - match:
          update_type: all
          update_type: all
{%- endif %}
